rango/urls.py
from django.urls import path, include
from rango import views

app_name = 'rango'
LOGIN_URL = 'rango:login'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('search/', views.search, name='search'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from rango import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', views.index, name='index'),
                  path('rango/', include('rango.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('registration.backends.simple.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *arg, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*arg, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category
from rango.models import UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    # An inline class to provide additional information on the form.


    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)


    class Meta:
        # Provide an association between the ModelForm and a model

        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,

        exclude = ('category',)
        # or specify the fields to include (i.e. not include the category field)
        # fields = ('title', 'url', 'views')

        def clean(self):
            cleaned_data = self.cleaned_data
            url = cleaned_data.get('url')
            # If url is not empty and doesn't start with 'http://',
            # then prepend 'http://'.
            if url and not url.startswith('http://'):
                url = 'http://' + url
                cleaned_data['url'] = url

                return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.http import HttpResponse
from rango.bing_search import run_query


# Create your views here.
def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)
    return response


def back_main(request):
    return render(request, 'rango/index.html', {})


def about(request):
    print(request.method)
    print(request.user)
    # return HttpResponse("Abouuuuuuuuuuuuut!")
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()

    return render(request, 'rango/about.html', {})


def show_category(request, category_name_slug):
    # 创建上下文字典，稍后传给模板渲染引擎
    context_dict = {}
    try:
        # 能通过传入的分类别名找到对应的分类吗？
        # 如果找不到，.get() 方法抛出 DoesNotExist 异常
        # 因此 .get() 方法返回一个模型实例或抛出异常
        category = Category.objects.get(slug=category_name_slug)
        # 检索关联的所有网页
        # 注意，filter() 返回一个网页对象列表或空列表
        pages = Page.objects.filter(category=category)
        # 把得到的列表赋值给模板上下文中名为 pages 的键
        context_dict['pages'] = pages
        # 也把从数据库中获取的 category 对象添加到上下文字典中
        # 我们将在模板中通过这个变量确认分类是否存在
        context_dict['category'] = category
    except Category.DoesNotExist:
        # 没找到指定的分类时执行这里
        # 什么也不做
        # 模板会显示消息，指明分类不存在
        context_dict['category'] = None
        context_dict['pages'] = None
    # 渲染响应，返回给客户端
    return render(request, 'rango/category.html', context_dict)


def add_category(request):
    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
    # Have we been provided with a valid form?
    if form.is_valid():
        # Save the new category to the database.
        form.save(commit=True)
        # Now that the category is saved
        # We could give a confirmation message
        # But since the most recent category added is on the index page
        # Then we can direct the user back to the index page.
        return index(request)
    else:
        # The supplied form contained errors -
        # just print them to the terminal.
        print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False
    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user
            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            # Now we save the UserProfile model instance.
            profile.save()
            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()
    # Render the template depending on the context.
    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")


# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))


# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    # Update/set the visits cookie
    request.session['visits'] = visits


def search(request):
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)
    return render(request, 'rango/search.html', {'result_list': result_list})

templates/rango/about.html
{% extends 'rango/base.html' %}

{% load staticfiles %} <!--New line -->

{% block body_block %}


<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Rango About</h1>
        <div>
            <h2 class="h2">
                Rango says...
                This tutorial has been put together by yzx
            </h2>
            <strong>{{ boldmessage }}</strong>
        </div>
    </div>
</div>

<div class="container">
    <div class="card-body">
		<h3><a href="/rango/about/">新的一天，开冲</a><br /></h3>
		<img src="{{MEDIA_URL}}chong.jpg"
			 alt="CHONG" />
	</div>
	<div>
		<a href="/rango/">回到主页</a><br />
	</div>
</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumotron-heading">Add a Category</h1>
        </div>
    </div>
        
    <div class="container">
        <div class="row">
            <form role="form" id="category_form" method="post" actions="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br />
                    {{ field }}<br />
                    <div class="p-2"></div>
                {% endfor %}
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Category
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
{% if category %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add Page to {{category.name}}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post"
              action=/populate_rango/{{category.slug}}/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br/>
            {{ field }}<br/>
            <div class="p-2"></div>
            {% endfor %}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% else %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumotron-heading">Add a Page</h1>
    </div>
</div>
<div>
    The specified category does not exist.
</div>
{% endif %}
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block title_block %}
{% if category %}
{{ category.name }}
{% else %}
Unknown Category
{% endif %}
{% endblock %}
{% block body_block %}
<div>
    {% block sidebar_block %}
    {% get_category_list category %}
    {% endblock %}
</div>
{% if category %}
<h1>{{ category.name }}</h1>
{% if pages %}
<hr/>
<ul>
    {% if user.is_authenticated %}
    <!-- Show these links when the user is logged in -->
    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
    {% else %}
    <!-- Show these links when the user is NOT logged in -->
    <li><a href="{% url 'rango:login' %}">Login</a></li>
    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
    {% endif %}
    <!-- Outside the conditional statements, ALWAYS show -->
    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
    <li><a href="{% url 'rango:about' %}">About</a></li>
    <li><a href="{% url 'rango:index' %}">Index</a></li>
</ul>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}
<a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
{% else %}
The specified category does not exist!
{% endif %}
{% endblock %}
</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator"
          content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css"
          rel="stylesheet">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
        <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'rango:add_category' %}">Add Category</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item ">
                    <a class="nav-link"
                       href="{% url 'rango:restricted' %}">Restricted</a></li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'rango:logout' %}?next=/rango/">Logout</a></li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link"
                       href="{% url 'registration_register' %}">Register Here</a></li>
                <li class="nav-item ">
                    <a class="nav-link"
                       href="{% url 'rango:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                {% block sidebar_block %}
                {% get_category_list category %}
                {% endblock %}
            </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block body_block %}
            {% endblock %}
            <footer>
                <p class="float-right"><a href="#">Back to top</a></p>
                <p>&copy; 2019 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot;
                    <a href="#">Terms</a></p>
            </footer>
        </main>
    </div>
</div>
<!-- Bootstrap core JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script>
window.jQuery || document.write('<script src="https://getbootstrap.com/
docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')

</script>
<script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/
feather.min.js">
</script>
<script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js">
</script>
</body>
</html>

templates/rango/categories.html
<!--<ul>-->
<!--{% if categories %}-->
<!--{% for c in categories %}-->
<!--{% if c == current_category %}-->
<!--<li>-->
<!--<strong>-->
<!--<a href="/rango/category/{{c.slug}}/">{{ c.name }}</a>-->
<!--</strong>-->
<!--</li>-->
<!--{% else %}-->
<!--<li>-->
<!--<a href="/rango/category/{{c.slug}}/">{{ c.name }}</a>-->
<!--</li>-->
<!--{% endif %}-->
<!--{% endfor %}-->
<!--{% else %}-->
<!--<li><strong>There are no categories present.</strong></li>-->
<!--{% endif %}-->
<!--</ul>-->

<ul class="nav flex-column">
    {% if categories %}
    {% for c in categories %}
    {% if c == current_category %}
    <li class="nav-item">
        <a class="nav-link active" href="/rango/category/{{c.slug}}/">
            <span data-feather="archive"></span>{{ c.name }}
        </a>
    </li>
    {% else %}
    <li class="nav-item">
        <a class="nav-link" href="/rango/category/{{c.slug}}/">
            <span data-feather="archive"></span>{{ c.name }}
        </a>
    </li>
    {% endif %}
    {% endfor %}
    {% else %}
    <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
    {% if category %}
    <h1>{{ category.name }}</h1>
    </div>
</div>
    <div class="container">

    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>

    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
    {% else %}
    <h4 The specified category does not exist! />
    {% endif %}
    </div>
</div>
{% endblock %}

templates/rango/cats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for c in cats %}
{% if c == act_cat %}
<li>
<strong>
<a href="{% url 'show_category' c.slug %}">{{ c.name }}</a>
</strong>
</li>
{% else %}
<li>
<a href="{% url 'show_category' c.slug %}">{{ c.name }}</a>
</li>
{% endif %}
{% endfor %}
</body>
</html>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %} <!--New line -->

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
            <h2 class="h2">
                {% if user.is_authenticated %}
                howdy {{ user.username }}!
                {% else %}
                hey there partner!
                {% endif %}
            </h2>
            <strong>{{ boldmessage }}</strong>
        </div>
    </div>
</div>
<div>
    {% if user.is_authenticated %}
    howdy {{ user.username }}!
    {% else %}
    hey there partner!
    <p>Visits: {{ visits }}</p>
    {% endif %}
    <strong>{{boldmessage}}</strong><br/>
</div>




<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Liked Categories</h2>
                    <p class="card-text">
                        {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                        <li class="list-group-item">
                            <a href="/rango/category/{{category.slug}}/">
                                {{ category.name }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no categories present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Viewed Pages</h2>
                    <p class="card-text">
                        {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{{ page.url }}">{{ page.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no pages present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <img src="{% static 'images/pig.gif' %}" alt="Picture of YY"/>
    <img src="{% static 'images/love1.gif' %}" alt="Picture of us"/>
</div>


{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css"
rel="stylesheet">
<div class="jumbotron p-4"> <h1 class="jumbotron-heading">Login</h1>
</div>
<div class="container">
<form class="form-signin" role="form" method="post" action="/rango/login/">
{% csrf_token %}
<label for="inputUsername" class="sr-only">Username</label> <input type="text" name="username" id="id_username" class="form-control"
placeholder="Username" required autofocus> <label for="inputPassword" class="sr-only">Password</label> <input type="password" name="password" id="id_password" class="form-control"
placeholder="Password" required>
<button class="btn btn-lg btn-primary btn-block" type="submit"
value="Submit">Sign in</button>
</form>
</div>
{% endblock %}

templates/rango/register.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Register
{% endblock %}
{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br/>
{% else %}
Rango says: <strong>register here!</strong><br/>
<form id="user_form" method="post" action="{% url 'rango:register' %}"
      enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Display each form -->
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register"/>
</form>
{% endif %}
{% endblock %}

templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumotron-heading">Search with Rango</h1>
        </div>
    </div>
    <div>
        <form class="form-inline" id="user-form" method="post" action="{% url 'rango:search' %}">
            {% csrf_token %}
            
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
            </div>
            
            <button class="btn btn-primary" type="submit" name="submit">Search</button>
        </form>
    </div>
    <div>
        {% if result_list %}
            <h2>Results</h2>
            
            <div class="list-group">
                {% for result in result_list %}
                    <div class="list-group-item">
                        <h3 class="list-group-item-heading">
                            <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
                        </h3>
                        <p class="list-group-item-text">{{ result.summary|safe|escape }}</p>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}